spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 3077263hhx

mybatis:
  type-aliases-package: com.example.lunar.model
  mapper-locations: classpath:mapper/*.xml
server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
